# Generated by Django 2.1 on 2021-06-06 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=255)),
                ('Email_Address', models.EmailField(max_length=254)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=50)),
                ('Age', models.PositiveIntegerField(null=True)),
                ('Date_of_birth', models.DateField(help_text='Please Enter the following in YYYY-MM-DD')),
                ('Aadhar_number', models.CharField(max_length=12, unique=True)),
                ('Marital_status', models.CharField(choices=[('Unmarried', 'Unmarried'), ('Married', 'Married'), ('Widow', 'Widow')], max_length=50)),
                ('Father_name', models.CharField(max_length=255)),
                ('Father_occupation', models.CharField(max_length=255)),
                ('Father_number', models.CharField(blank=True, help_text='If minor, Please mention', max_length=10, null=True)),
                ('Mother_name', models.CharField(max_length=255)),
                ('Mother_occupation', models.CharField(max_length=255)),
                ('Guardian_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Guardian_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('Mobile_number', models.CharField(max_length=10)),
                ('Address_1', models.CharField(max_length=900)),
                ('Address_2', models.CharField(blank=True, max_length=900, null=True)),
                ('City', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('Zipcode', models.CharField(max_length=8)),
                ('Annual_income', models.PositiveIntegerField(null=True)),
                ('Caste', models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], max_length=50)),
                ('Community', models.CharField(choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Christianity', 'Christianity'), ('Others', 'Others')], max_length=50)),
                ('course_pursuing', models.CharField(help_text='eg: B.sc,B.tech,...', max_length=255)),
                ('specialization', models.CharField(help_text='eg: ECE,Pharmacy,Nursing,...', max_length=255)),
                ('roll_number', models.CharField(help_text='eg: university roll number', max_length=8)),
                ('mark_in_higher_school', models.CharField(help_text='Enter it in marks or average eg: 6.9,8.8', max_length=5)),
                ('mark_in_secondary_school', models.CharField(help_text='Enter it in points eg: 6.9,8.8', max_length=5)),
                ('Education_mode', models.CharField(choices=[('Day scholar', 'Day scholar'), ('Hosteller', 'Hosteller'), ('Correspondence', 'Correspondence')], max_length=50)),
                ('scholarship', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='Availing any scholarship already? If yes, Please mention below', max_length=50)),
                ('mention_scholarship', models.CharField(blank=True, help_text='if not leave blank', max_length=500, null=True)),
                ('disability', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='do you have any disabilities? If yes, Please mention below', max_length=50)),
                ('mention', models.CharField(blank=True, help_text='if disability please mention', max_length=500, null=True)),
                ('applying_for', models.CharField(choices=[('Student', 'Student'), ('Disability', 'Disability'), ('Widow', 'Widow'), ('Marriage', 'Marriage'), ('BPL', 'BPL'), ('Caste', 'Caste'), ('Senior Citizen', 'Senior Citizen')], help_text='You"re applying for', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
